language: "en-US"
early_access: false

reviews:
  profile: "chill"  # Options: 'chill', 'strict', etc.
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  collapse_walkthrough: true
  path_filters:
    - "*.cs"       # Include C# source files
    - "!assets/**" # Exclude asset files
    - "!addons/**" # Exclude third-party addons
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
    drafts: false
    max_file_changes: 10  # Flag large PRs for manual review
    min_approval_required: 1 # Require at least 1 approval for merges

chat:
  auto_reply: true

knowledge_base:
  jira:
    project_keys: []  # Add your Jira project keys if integrating
  linear:
    team_keys: []     # Add your Linear team keys if integrating

tools:
  ast_grep:
    essential_rules: true
    rule_dirs: []
    packages: []

# Add any path-specific review instructions if needed
path_instructions:
  - path: "**/*.cs"
    instructions: |
      Ensure the C# code adheres to the project's coding standards and best practices.
