language: "en-US"
early_access: false

reviews:
  profile: "chill"  # Options: 'chill', 'strict', etc.
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
    drafts: false

chat:
  auto_reply: true

